// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrrnprfymzagkxcwycrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlycm5wcmZ5bXphZ2t4Y3d5Y3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMzQ0NjAsImV4cCI6MjA1MjgxMDQ2MH0.3YHFodoZiBrUiaufb4eYh3Jhx0cY0nixgFW1BcIfzMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);